name: Deploy app on master merge

on:
  # push:
  #   branches:
  #     - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-22.04

    steps:
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::056984988198:role/GitHubActionsECRPushf22f2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: user/app:latest

    

      # - run: |
      #     docker build -t docker-on-aws-tf/nodejs .
      #     docker tag docker-on-aws-tf/nodejs:latest 056984988198.dkr.ecr.eu-west-3.amazonaws.com/docker-on-aws-tf/nodejs:latest
      #     docker push 056984988198.dkr.ecr.eu-west-3.amazonaws.com/docker-on-aws-tf/nodejs:latest